name: Scoreboard
version: '${project.version}'
main: de.lundlucenany9.scoreboard.Scoreboard
api-version: '1.19'
commands:
  rank:
    description: Gives a player a rank.
    usage: /rank <Player> <Rank>
    permission: scoreboard.rank
  pay:
    description: Pay money to somebody.
    usage: /pay <Player> <Money>
    permission: scoreboard.pay
  eco:
    description: gives, removes money from a player
    usage: /eco <Player> <add|take|set|get> <Money>
    permission: scoreboard.eco
  get:
    usage: /get <Player>
    permission: scoreboard.get
  job:
    usage: /job [Player] [Job]
    description: Sezt oder zeigt den Job eines Spielers.
    permission: scoreboard.job
permissions:
  scoreboard.rank:
    description: The permission to use the rank command.
    default: op
  scoreboard.pay:
    description: The permission to use the pay command.
    default: true
  scoreboard.eco:
    description: The permission to use the eco command.
    default: op
  scoreboard.get:
    default: op
  scoreboard.job:
    default: true
    children:
      - scoreboard.job.other
  scoreboard.job.other:
    default: op
    children:
      - scoreboard.job.other.change: false
  scoreboard.job.other.change:
    default: op